### PR TITLE
Dont move the consumer to user space

### PR DESCRIPTION
**Pull request by Nyholm**
This is an alternative approach for the package. Currently we just copy some files to `/src` and let the user handle the implementation. 

With this PR we keep the code in `/vendor` and allow the user to interact with the SNS event using Symfony events. 
Im not sure what I like the most...

### CODE REVIEW

**Comment by mnapoli** [comment]
That sounds reasonable, copying entire classes to the user's project will pose issues with upgrading/fixing bugs/adding features.

**Comment by Nyholm** [comment]
Thank you for the review.

Could you add this package to packagist?

**Comment by mnapoli** [comment]
That's on Packagist!

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
